###

// 城际用车查询出发城市/目的城市列表
// type       类型，0：出发城市；1：目的城市
// cityCode   城市行政区划编码（查终点传起点编码，查起点传终点编码）
POST https://api.cloud.ynpay.cc/client?action=pd04/city/list HTTP/1.1
Authorization: Bearer ffdd622f-5e37-4cc3-9d27-314422f7dcb0
Content-Type: application/json

{
	"action": "pd04/city/list",
	"payload": {
    "cityCode": "530100",
    "type": 0
	}
}


###

// 城际用车查询热门城市
POST https://api.cloud.ynpay.cc/client?action=pd04/city/hot HTTP/1.1
Authorization: Bearer ffdd622f-5e37-4cc3-9d27-314422f7dcb0
Content-Type: application/json

{
	"action": "pd04/city/hot"
}


###

// 城际用车查询历史查询记录
POST https://api.cloud.ynpay.cc/client?action=pd04/cityHistory/list HTTP/1.1
Authorization: Bearer c3fe9236-1117-4ca9-b95e-7331ea60d70b
Content-Type: application/json

{
	"action": "pd04/cityHistory/list"
}


###

// 城际用车删除历史查询记录
POST https://api.cloud.ynpay.cc/client?action=pd04/cityHistory/del HTTP/1.1
Authorization: Bearer fdae29ac-8238-4bd3-ae56-8b5543e26a10
Content-Type: application/json

{
	"action": "pd04/cityHistory/del"
}


###

// 城际用车班次查询
POST https://api.cloud.ynpay.cc/client?action=pd04/schedule/list HTTP/1.1
Authorization: Bearer c3fe9236-1117-4ca9-b95e-7331ea60d70b
Content-Type: application/json

{
	"action": "pd04/schedule/list",
  "payload": {
    "cityCode": "530100",
    "toCityCode": "530600",
    "useDate": "2020-04-28"
  }
}


###

// 城际用车班次详情查询
POST https://api.cloud.ynpay.cc/client?action=pd04/schedule/info HTTP/1.1
Authorization: Bearer c3fe9236-1117-4ca9-b95e-7331ea60d70b
Content-Type: application/json

{
	"action": "pd04/schedule/info",
  "payload": {
    "code": "G20042700000009031"
  }
}


###

// 城际用车自定义上下车位置校验有效性并返回匹配的出发地或目的地围栏
// type：类型，depart：上车位置；arrive：下车位置
POST https://api.cloud.ynpay.cc/client?action=pd04/choose/geo HTTP/1.1
Authorization: Bearer bbc33108-ab80-411b-b1de-58a7db4dacf
Content-Type: application/json

{
	"action": "pd04/choose/geo",
  "payload": {
    "productCode": "P20042100000001250",
    "type": "arrive",
    "location": {
      "name": "昭通机场",
      "address": "昭通机场",
      "geo": {
        "type": "Point",
        "coordinates": [103.757674,27.323525]
      },
      "geoType": "GCJ02"
    }
  }
}


###

// 查询乘车人列表
POST https://api.cloud.ynpay.cc/client?action=passenger/query/list HTTP/1.1
Authorization: Bearer 2f98eecc-efd0-44ec-91d0-a9ce75ed21a1
Content-Type: application/json



###

// 添加乘车人
POST https://api.cloud.ynpay.cc/client?action=passenger/create HTTP/1.1
Authorization: Bearer 2f98eecc-efd0-44ec-91d0-a9ce75ed21a1
Content-Type: application/json

{
  "action": "passenger/create",
  "payload": {
    "cardType": "01",
    "cardNo": "43052219871207393X",
    "name": "龙文纳"
  }
}


###

// 删除乘车人
POST https://api.cloud.ynpay.cc/client?action=passenger/delete url HTTP/1.1 HTTP/1.1
Authorization: Bearer 2f98eecc-efd0-44ec-91d0-a9ce75ed21a1
Content-Type: application/json

{
  "action": "passenger/delete",
  "payload": {
    "codes": ["P19031400000004125"]
  }
}


###

// 修改乘车人
POST https://api.cloud.ynpay.cc/client?action=passenger/modify url HTTP/1.1 HTTP/1.1
Authorization: Bearer 2f98eecc-efd0-44ec-91d0-a9ce75ed21a1
Content-Type: application/json

{
  "action": "passenger/modify",
  "payload": {
    "id": "5ea101106739b000013c5500",
    "cardType": "01",
    "cardNo": "43052219871207393X",
    "name": "龙文纳"
  }
}


###

// 城际用车下单
POST https://api.cloud.ynpay.cc/client?action=pd04/order/create url HTTP/1.1 HTTP/1.1
Authorization: Bearer afe1fbff-4817-4233-b96f-979e73bd4b24
Content-Type: application/json

{
  "action": "pd04/order/create",
  "payload": {
    "groupCode": "G20042700000011897",
    "linkman": {
      "name": "龙文纳",
      "mobile": "18669116234"
    },
    "depart": {
      "name": "北部客运站",
      "address": "昆明北部客运站站前广场",
      "geo": {
        "type": "Point",
        "coordinates": [102.763204, 25.108778]
      },
      "geoType": "GCJ02"
    },
    "arrive": {
      "name": "昭通市政府",
      "address": "云南省昭通市昭阳区崇义街30号",
      "geo": {
        "type": "Point",
        "coordinates": [103.717191,27.337984]
      },
      "geoType": "GCJ02"
    },
    "departCode": "F19021400000009145",
    "arriveCode": "F19111300000652139",
   // "useTime": "",
    "seats": [
      {
        "seatNo": 1,
        // 是否儿童座，0：否；1：是
        "childSeat": 1,
        "passenger": {
          "cardType": "01",
          "cardNo": "43052219871207393X",
          "name": "龙文纳"
        }
      },
      {
        "seatNo": 2,
        "childSeat": 0,
        "passenger": {
          "cardType": "01",
          "cardNo": "452702198812251888",
          "name": "谭荣庆"
        }
      }
    ],
    "scene": "default",
    // 微信openid
    "openid": "odwiK5cm4kMDNSnzfGelkhSaTWmI",
    "desc": ""
  }
}


###

// 城际用车查询订单详情
POST https://api.cloud.ynpay.cc/client?action=order/info url HTTP/1.1 HTTP/1.1
Authorization: Bearer 88c05045-83c5-41c5-a291-f1b75e00bd29
Content-Type: application/json

{
  "action": "order/info",
  "payload": {
    "superNo": "S20042400000005837"
  }
}


###

// 城际用车查询订单退票手续费
// superNo和orderNos不能同时为空，如果orderNos不为空则忽略superNo取orderNos。
POST https://api.cloud.ynpay.cc/client?action=order/refundFee url HTTP/1.1 HTTP/1.1
Authorization: Bearer 88c05045-83c5-41c5-a291-f1b75e00bd29
Content-Type: application/json

{
  "action": "order/refundFee",
  "payload": {
    // "superNo": "S20042400000005837",
    "orderNos": ["D20042400000006288", "D20042400000007871"]
  }
}


###

// 城际用车订单退票
POST https://api.cloud.ynpay.cc/client?action=order/refundFee url HTTP/1.1 HTTP/1.1
Authorization: Bearer 88c05045-83c5-41c5-a291-f1b75e00bd29
Content-Type: application/json

{
  "action": "order/refundFee",
  "payload": {
    // "superNo": "S20042400000005837",
    "orderNos": ["D20042400000006288", "D20042400000007871"]
  }
}


###

// 城际用车订单批量退票
POST https://api.cloud.ynpay.cc/client?action=order/refundFee url HTTP/1.1 HTTP/1.1
Authorization: Bearer 88c05045-83c5-41c5-a291-f1b75e00bd29
Content-Type: application/json

{
  "action": "order/refundFee",
  "payload": {
    // "superNo": "S20042400000005837",
    "orderNos": ["D20042400000006288", "D20042400000007871"]
  }
}






###

// 政企用车下单
POST https://api.cloud.ynpay.cc/client?action=pd02/orderCreate url HTTP/1.1 HTTP/1.1
Authorization: Bearer 88c05045-83c5-41c5-a291-f1b75e00bd29
Content-Type: application/json

{
  "stationCode":"KMNZ",
  "estimatePriceNo":"d9550aa8-6ed3-4dac-9b02-4fb6a20b93fe",
  "linkman":{
    "mobile":"18669116234"
  },
  "category":22,
  "enterpriseCode":"666666",
  "desc": "备注",
  "shipInfo": {
    "type": "FLIGHT",  // FLIGHT：飞机；CRH：动车/高铁
    "no": "KY8254",
    "datetime": "2020-05-12 12:30",  // 出发/到达时间
    "desc": ""  // 航班、高铁描述
  }
}

